const doramasData = [
  { id: 1, title: "Силачка До Бон-сун", genres: ["Комедия", "Романтика"], banner: "pictures/banner/1.jpg", images: ["pictures/screenshot/(1)/1 (1).jpg", "pictures/screenshot/(1)/1 (2).jpg", "pictures/screenshot/(1)/1 (3).jpg", "pictures/screenshot/(1)/1 (4).jpg", "pictures/screenshot/(1)/1 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 2, title: "Что случилось с секретарем Ким?", genres: ["Романтика"], banner: "pictures/banner/2.jpg", images: ["pictures/screenshot/(2)/2 (1).jpg", "pictures/screenshot/(2)/2 (2).jpg", "pictures/screenshot/(2)/2 (3).jpg", "pictures/screenshot/(2)/2 (4).jpg", "pictures/screenshot/(2)/2 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 3, title: "Продавец на полставки", genres: ["Комедия"], banner: "pictures/banner/3.jpg", images: ["pictures/screenshot/(3)/3 (1).jpg", "pictures/screenshot/(3)/3 (2).jpg", "pictures/screenshot/(3)/3 (3).jpg", "pictures/screenshot/(3)/3 (4).jpg", "pictures/screenshot/(3)/3 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 4, title: "Демон (Гоблин)", genres: ["Фэнтези"], banner: "pictures/banner/4.jpg", images: ["pictures/screenshot/(4)/4 (1).jpg", "pictures/screenshot/(4)/4 (2).jpg", "pictures/screenshot/(4)/4 (3).jpg", "pictures/screenshot/(4)/4 (4).jpg", "pictures/screenshot/(4)/4 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 5, title: "Наследники", genres: ["Романтика"], banner: "pictures/banner/5.jpg", images: ["pictures/screenshot/(5)/5 (1).jpg", "pictures/screenshot/(5)/5 (2).jpg", "pictures/screenshot/(5)/5 (3).jpg", "pictures/screenshot/(5)/5 (4).jpg", "pictures/screenshot/(5)/5 (5).jpg"], status: "брошено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 6, title: "Фея тяжелой атлетики Ким Бок-чжу", genres: ["Спорт", "Романтика"], banner: "pictures/banner/6.jpg", images: ["pictures/screenshot/(6)/6 (1).jpg", "pictures/screenshot/(6)/6 (2).jpg", "pictures/screenshot/(6)/6 (3).jpg", "pictures/screenshot/(6)/6 (4).jpg", "pictures/screenshot/(6)/6 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 7, title: "Уведомление о любви", genres: ["Романтика"], banner: "pictures/banner/7.jpg", images: ["pictures/screenshot/(7)/7 (1).jpg", "pictures/screenshot/(7)/7 (2).jpg", "pictures/screenshot/(7)/7 (3).jpg", "pictures/screenshot/(7)/7 (4).jpg", "pictures/screenshot/(7)/7 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 8, title: "Каннамская красотка", genres: ["Романтика"], banner: "pictures/banner/8.jpg", images: ["pictures/screenshot/(8)/8 (1).jpg", "pictures/screenshot/(8)/8 (2).jpg", "pictures/screenshot/(8)/8 (3).jpg", "pictures/screenshot/(8)/8 (4).jpg", "pictures/screenshot/(8)/8 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 9, title: "Королева слез", genres: ["Драма", "Романтика"], banner: "pictures/banner/9.jpg", images: ["pictures/screenshot/(9)/9 (1).jpg", "pictures/screenshot/(9)/9 (2).jpg", "pictures/screenshot/(9)/9 (3).jpg", "pictures/screenshot/(9)/9 (4).jpg", "pictures/screenshot/(9)/9 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 10, title: "Вернуться в 1988", genres: ["Комедия", "Драма"], banner: "pictures/banner/10.jpg", images: ["pictures/screenshot/(10)/10 (1).jpg", "pictures/screenshot/(10)/10 (2).jpg", "pictures/screenshot/(10)/10 (3).jpg", "pictures/screenshot/(10)/10 (4).jpg", "pictures/screenshot/(10)/10 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 11, title: "Алхимия душ", genres: ["Фэнтези", "Экшен"], banner: "pictures/banner/11.jpg", images: ["pictures/screenshot/(11)/11 (1).jpg", "pictures/screenshot/(11)/11 (2).jpg", "pictures/screenshot/(11)/11 (3).jpg", "pictures/screenshot/(11)/11 (4).jpg", "pictures/screenshot/(11)/11 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 12, title: "Плохая мать", genres: ["Драма"], banner: "pictures/banner/12.jpg", images: ["pictures/screenshot/(12)/12 (1).jpg", "pictures/screenshot/(12)/12 (2).jpg", "pictures/screenshot/(12)/12 (3).jpg", "pictures/screenshot/(12)/12 (4).jpg", "pictures/screenshot/(12)/12 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 13, title: "Призрачный доктор", genres: ["Фэнтези", "Медицина"], banner: "pictures/banner/13.jpg", images: ["pictures/screenshot/(13)/13 (1).jpg", "pictures/screenshot/(13)/13 (2).jpg", "pictures/screenshot/(13)/13 (3).jpg", "pictures/screenshot/(13)/13 (4).jpg", "pictures/screenshot/(13)/13 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 14, title: "Врачебная мудрость", genres: ["Медицина", "Драма"], banner: "pictures/banner/14.jpg", images: ["pictures/screenshot/(14)/14 (1).jpg", "pictures/screenshot/(14)/14 (2).jpg", "pictures/screenshot/(14)/14 (3).jpg", "pictures/screenshot/(14)/14 (4).jpg", "pictures/screenshot/(14)/14 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 15, title: "Завтра", genres: ["Фэнтези"], banner: "pictures/banner/15.jpg", images: ["pictures/screenshot/(15)/15 (1).jpg", "pictures/screenshot/(15)/15 (2).jpg", "pictures/screenshot/(15)/15 (3).jpg", "pictures/screenshot/(15)/15 (4).jpg", "pictures/screenshot/(15)/15 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 16, title: "Хилер", genres: ["Экшен", "Романтика"], banner: "pictures/banner/16.jpg", images: ["pictures/screenshot/(16)/16 (1).jpg", "pictures/screenshot/(16)/16 (2).jpg", "pictures/screenshot/(16)/16 (3).jpg", "pictures/screenshot/(16)/16 (4).jpg", "pictures/screenshot/(16)/16 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 17, title: "Потомки солнца", genres: ["Романтика", "Военный"], banner: "pictures/banner/17.jpg", images: ["pictures/screenshot/(17)/17 (1).jpg", "pictures/screenshot/(17)/17 (2).jpg", "pictures/screenshot/(17)/17 (3).jpg", "pictures/screenshot/(17)/17 (4).jpg", "pictures/screenshot/(17)/17 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 18, title: "Мама", genres: ["Драма"], banner: "pictures/banner/18.jpg", images: ["pictures/screenshot/(18)/18 (1).jpg", "pictures/screenshot/(18)/18 (2).jpg", "pictures/screenshot/(18)/18 (3).jpg", "pictures/screenshot/(18)/18 (4).jpg", "pictures/screenshot/(18)/18 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 19, title: "Учитель Ким, доктор романтик", genres: ["Медицина"], banner: "pictures/banner/19.jpg", images: ["pictures/screenshot/(19)/19 (1).jpg", "pictures/screenshot/(19)/19 (2).jpg", "pictures/screenshot/(19)/19 (3).jpg", "pictures/screenshot/(19)/19 (4).jpg", "pictures/screenshot/(19)/19 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 20, title: "Хватай Сон Джэ и беги", genres: ["Романтика", "Фэнтези"], banner: "pictures/banner/20.jpg", images: ["pictures/screenshot/(20)/20 (1).jpg", "pictures/screenshot/(20)/20 (2).jpg", "pictures/screenshot/(20)/20 (3).jpg", "pictures/screenshot/(20)/20 (4).jpg", "pictures/screenshot/(20)/20 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 21, title: "Я псих, но это нормально", genres: ["Психология", "Романтика"], banner: "pictures/banner/21.jpg", images: ["pictures/screenshot/(21)/21 (1).jpg", "pictures/screenshot/(21)/21 (2).jpg", "pictures/screenshot/(21)/21 (3).jpg", "pictures/screenshot/(21)/21 (4).jpg", "pictures/screenshot/(21)/21 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 22, title: "Время взывает к тебе", genres: ["Фэнтези", "Романтика"], banner: "pictures/banner/22.jpg", images: ["pictures/screenshot/(22)/22 (1).jpg", "pictures/screenshot/(22)/22 (2).jpg", "pictures/screenshot/(22)/22 (3).jpg", "pictures/screenshot/(22)/22 (4).jpg", "pictures/screenshot/(22)/22 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 23, title: "Итэвон Класс", genres: ["Бизнес", "Драма"], banner: "pictures/banner/23.jpg", images: ["pictures/screenshot/(23)/23 (1).jpg", "pictures/screenshot/(23)/23 (2).jpg", "pictures/screenshot/(23)/23 (3).jpg", "pictures/screenshot/(23)/23 (4).jpg", "pictures/screenshot/(23)/23 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 24, title: "И солнце снова взойдет", genres: ["Драма", "Медицина"], banner: "pictures/banner/24.jpg", images: ["pictures/screenshot/(24)/24 (1).jpg", "pictures/screenshot/(24)/24 (2).jpg", "pictures/screenshot/(24)/24 (3).jpg", "pictures/screenshot/(24)/24 (4).jpg", "pictures/screenshot/(24)/24 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 25, title: "Любовное приземление", genres: ["Романтика", "Комедия"], banner: "pictures/banner/25.jpg", images: ["pictures/screenshot/(25)/25 (1).jpg", "pictures/screenshot/(25)/25 (2).jpg", "pictures/screenshot/(25)/25 (3).jpg", "pictures/screenshot/(25)/25 (4).jpg", "pictures/screenshot/(25)/25 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 26, title: "Мышь", genres: ["Триллер", "Детектив"], banner: "pictures/banner/26.jpg", images: ["pictures/screenshot/(26)/26 (1).jpg", "pictures/screenshot/(26)/26 (2).jpg", "pictures/screenshot/(26)/26 (3).jpg", "pictures/screenshot/(26)/26 (4).jpg", "pictures/screenshot/(26)/26 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 27, title: "Дьявольский судья", genres: ["Детектив", "Закон"], banner: "pictures/banner/27.jpg", images: ["pictures/screenshot/(27)/27 (1).jpg", "pictures/screenshot/(27)/27 (2).jpg", "pictures/screenshot/(27)/27 (3).jpg", "pictures/screenshot/(27)/27 (4).jpg", "pictures/screenshot/(27)/27 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""}, 
  { id: 28, title: "Легенда синего моря", genres: ["Фэнтези", "Романтика"], banner: "pictures/banner/28.jpg", images: ["pictures/screenshot/(28)/28 (1).jpg", "pictures/screenshot/(28)/28 (2).jpg", "pictures/screenshot/(28)/28 (3).jpg", "pictures/screenshot/(28)/28 (4).jpg", "pictures/screenshot/(28)/28 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 29, title: "Любовное сражение", genres: ["Комедия", "Романтика"], banner: "pictures/banner/29.jpg", images: ["pictures/screenshot/(29)/29 (1).jpg", "pictures/screenshot/(29)/29 (2).jpg", "pictures/screenshot/(29)/29 (3).jpg", "pictures/screenshot/(29)/29 (4).jpg", "pictures/screenshot/(29)/29 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 30, title: "Болтун", genres: ["Триллер", "Закон"], banner: "pictures/banner/30.jpg", images: ["pictures/screenshot/(30)/30 (1).jpg", "pictures/screenshot/(30)/30 (2).jpg", "pictures/screenshot/(30)/30 (3).jpg", "pictures/screenshot/(30)/30 (4).jpg", "pictures/screenshot/(30)/30 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 31, title: "Добро пожаловать в Самдали", genres: ["Романтика", "Повседневность"], banner: "pictures/banner/31.jpg", images: ["pictures/screenshot/(31)/31 (1).jpg", "pictures/screenshot/(31)/31 (2).jpg", "pictures/screenshot/(31)/31 (3).jpg", "pictures/screenshot/(31)/31 (4).jpg", "pictures/screenshot/(31)/31 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 32, title: "Военный прокурор Доберман", genres: ["Экшен", "Закон"], banner: "pictures/banner/32.jpg", images: ["pictures/screenshot/(32)/32 (1).jpg", "pictures/screenshot/(32)/32 (2).jpg", "pictures/screenshot/(32)/32 (3).jpg", "pictures/screenshot/(32)/32 (4).jpg", "pictures/screenshot/(32)/32 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 33, title: "Разрушение к вашим услугам", genres: ["Фэнтези", "Романтика"], banner: "pictures/banner/33.jpg", images: ["pictures/screenshot/(33)/33 (1).jpg", "pictures/screenshot/(33)/33 (2).jpg", "pictures/screenshot/(33)/33 (3).jpg", "pictures/screenshot/(33)/33 (4).jpg", "pictures/screenshot/(33)/33 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 34, title: "Счастье", genres: ["Триллер", "Зомби"], banner: "pictures/banner/34.jpg", images: ["pictures/screenshot/(34)/34 (1).jpg", "pictures/screenshot/(34)/34 (2).jpg", "pictures/screenshot/(34)/34 (3).jpg", "pictures/screenshot/(34)/34 (4).jpg", "pictures/screenshot/(34)/34 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 35, title: "Я не робот", genres: ["Романтика", "Комедия"], banner: "pictures/banner/35.jpg", images: ["pictures/screenshot/(35)/35 (1).jpg", "pictures/screenshot/(35)/35 (2).jpg", "pictures/screenshot/(35)/35 (3).jpg", "pictures/screenshot/(35)/35 (4).jpg", "pictures/screenshot/(35)/35 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 36, title: "Необычный адвокат У Ён У", genres: ["Закон", "Драма"], banner: "pictures/banner/36.jpg", images: ["pictures/screenshot/(36)/36 (1).jpg", "pictures/screenshot/(36)/36 (2).jpg", "pictures/screenshot/(36)/36 (3).jpg", "pictures/screenshot/(36)/36 (4).jpg", "pictures/screenshot/(36)/36 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 37, title: "Работай позже, пей сейчас", genres: ["Комедия", "Повседневность"], banner: "pictures/banner/37.jpg", images: ["pictures/screenshot/(37)/37 (1).jpg", "pictures/screenshot/(37)/37 (2).jpg", "pictures/screenshot/(37)/37 (3).jpg", "pictures/screenshot/(37)/37 (4).jpg", "pictures/screenshot/(37)/37 (5).jpg"], status: "брошено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 38, title: "Большое зло", genres: ["Триллер"], banner: "pictures/banner/38.jpg", images: ["pictures/screenshot/(38)/38 (1).jpg", "pictures/screenshot/(38)/38 (2).jpg", "pictures/screenshot/(38)/38 (3).jpg", "pictures/screenshot/(38)/38 (4).jpg", "pictures/screenshot/(38)/38 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 39, title: "Винченцо", genres: ["Криминал", "Комедия"], banner: "pictures/banner/39.jpg", images: ["pictures/screenshot/(39)/39 (1).jpg", "pictures/screenshot/(39)/39 (2).jpg", "pictures/screenshot/(39)/39 (3).jpg", "pictures/screenshot/(39)/39 (4).jpg", "pictures/screenshot/(39)/39 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 40, title: "ПУСТО", genres: ["Ужасы", "Не для детей"], banner: "pictures/banner/().jpg", images: ["pictures/screenshot/(40)/40 (1).jpg", "pictures/screenshot/(40)/40 (2).jpg", "pictures/screenshot/(40)/40 (3).jpg", "pictures/screenshot/(40)/40 (4).jpg", "pictures/screenshot/(40)/40 (5).jpg"], status: "брошено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: "Тут настолько пусто, что даже перекати поле нет"},
  { id: 41, title: "Цветок зла", genres: ["Триллер", "Детектив"], banner: "pictures/banner/41.jpg", images: ["pictures/screenshot/(41)/41 (1).jpg", "pictures/screenshot/(41)/41 (2).jpg", "pictures/screenshot/(41)/41 (3).jpg", "pictures/screenshot/(41)/41 (4).jpg", "pictures/screenshot/(41)/41 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 42, title: "Убей меня, исцели меня", genres: ["Психология", "Романтика"], banner: "pictures/banner/42.jpg", images: ["pictures/screenshot/(42)/42 (1).jpg", "pictures/screenshot/(42)/42 (2).jpg", "pictures/screenshot/(42)/42 (3).jpg", "pictures/screenshot/(42)/42 (4).jpg", "pictures/screenshot/(42)/42 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 43, title: "Плохой и сумасшедший", genres: ["Экшен", "Комедия"], banner: "pictures/banner/43.jpg", images: ["pictures/screenshot/(43)/43 (1).jpg", "pictures/screenshot/(43)/43 (2).jpg", "pictures/screenshot/(43)/43 (3).jpg", "pictures/screenshot/(43)/43 (4).jpg", "pictures/screenshot/(43)/43 (5).jpg"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 44, title: "Сказание о кумихо (История девятихвостого лиса)", genres: ["Фэнтези"], banner: "pictures/banner/44.jpg", images: ["pictures/screenshot/(44)/44 (1).jpg", "pictures/screenshot/(44)/44 (2).jpg", "pictures/screenshot/(44)/44 (3).jpg", "pictures/screenshot/(44)/44 (4).jpg", "pictures/screenshot/(44)/44 (5).jpg"], status: "брошено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 45, title: "Я тебя слышу", genres: ["Романтика", "Закон"], banner: "pictures/banner/45.jpg", images: ["pictures/screenshot/(45)/45 (1).jpg", "pictures/screenshot/(45)/45 (2).jpg", "pictures/screenshot/(45)/45 (3).jpg", "pictures/screenshot/(45)/45 (4).jpg", "pictures/screenshot/(45)/45 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 46, title: "Деловое предложение", genres: ["Романтика", "Комедия"], banner: "pictures/banner/46.jpg", images: ["pictures/screenshot/(46)/46 (1).jpg", "pictures/screenshot/(46)/46 (2).jpg", "pictures/screenshot/(46)/46 (3).jpg", "pictures/screenshot/(46)/46 (4).jpg", "pictures/screenshot/(46)/46 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 47, title: "Магазин для киллеров", genres: ["Экшен", "Триллер"], banner: "pictures/banner/47.jpg", images: ["pictures/screenshot/(47)/47 (1).jpg", "pictures/screenshot/(47)/47 (2).jpg", "pictures/screenshot/(47)/47 (3).jpg", "pictures/screenshot/(47)/47 (4).jpg", "pictures/screenshot/(47)/47 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 48, title: "Мой демон", genres: ["Фэнтези", "Романтика"], banner: "pictures/banner/48.jpg", images: ["pictures/screenshot/(48)/48 (1).jpg", "pictures/screenshot/(48)/48 (2).jpg", "pictures/screenshot/(48)/48 (3).jpg", "pictures/screenshot/(48)/48 (4).jpg", "pictures/screenshot/(48)/48 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 49, title: "Суждено быть с тобой", genres: ["Романтика", "Фэнтези"], banner: "pictures/banner/49.jpg", images: ["pictures/screenshot/(49)/49 (1).jpg", "pictures/screenshot/(49)/49 (2).jpg", "pictures/screenshot/(49)/49 (3).jpg", "pictures/screenshot/(49)/49 (4).jpg", "pictures/screenshot/(49)/49 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 50, title: "Хваюги", genres: ["Фэнтези", "Романтика", "Комедия"], banner: "pictures/banner/50.jpg", images: ["pictures/screenshot/(50)/50 (1).jpg", "pictures/screenshot/(50)/50 (2).jpg", "pictures/screenshot/(50)/50 (3).jpg", "pictures/screenshot/(50)/50 (4).jpg", "pictures/screenshot/(50)/50 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 51, title: "Отель Дель Луна", genres: ["Фэнтези"], banner: "pictures/banner/51.jpg", images: ["pictures/screenshot/(51)/51 (1).jpg", "pictures/screenshot/(51)/51 (2).jpg", "pictures/screenshot/(51)/51 (3).jpg", "pictures/screenshot/(51)/51 (4).jpg", "pictures/screenshot/(51)/51 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 52, title: "Ночная фотостудия", genres: ["Фэнтези", "Драма"], banner: "pictures/banner/52.jpg", images: ["pictures/screenshot/(52)/52 (1).jpg", "pictures/screenshot/(52)/52 (2).jpg", "pictures/screenshot/(52)/52 (3).jpg", "pictures/screenshot/(52)/52 (4).jpg", "pictures/screenshot/(52)/52 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 53, title: "Врачи", genres: ["Медицина", "Романтика"], banner: "pictures/banner/53.jpg", images: ["pictures/screenshot/(53)/53 (1).jpg", "pictures/screenshot/(53)/53 (2).jpg", "pictures/screenshot/(53)/53 (3).jpg", "pictures/screenshot/(53)/53 (4).jpg", "pictures/screenshot/(53)/53 (5).jpg"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 54, title: "Истинная красота", genres: ["Романтика", "Школа"], banner: "pictures/banner/54.jpg", images: ["pictures/screenshot/(54)/54 (1).jpg", "pictures/screenshot/(54)/54 (2).jpg", "pictures/screenshot/(54)/54 (3).jpg", "pictures/screenshot/(54)/54 (4).jpg", "pictures/screenshot/(54)/54 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 55, title: "Жизнь на Марсе", genres: ["Детектив", "Фантастика"], banner: "pictures/banner/55.jpg", images: ["pictures/screenshot/(55)/55 (1).jpg", "pictures/screenshot/(55)/55 (2).jpg", "pictures/screenshot/(55)/55 (3).jpg", "pictures/screenshot/(55)/55 (4).jpg", "pictures/screenshot/(55)/55 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 56, title: "Наше любимое лето", genres: ["Романтика", "Повседневность"], banner: "pictures/banner/56.jpg", images: ["pictures/screenshot/(56)/56 (1).jpg", "pictures/screenshot/(56)/56 (2).jpg", "pictures/screenshot/(56)/56 (3).jpg", "pictures/screenshot/(56)/56 (4).jpg", "pictures/screenshot/(56)/56 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 57, title: "Кто ты: Школа 2015", genres: ["Школа", "Драма"], banner: "pictures/banner/57.jpg", images: ["pictures/screenshot/(57)/57 (1).jpg", "pictures/screenshot/(57)/57 (2).jpg", "pictures/screenshot/(57)/57 (3).jpg", "pictures/screenshot/(57)/57 (4).jpg", "pictures/screenshot/(57)/57 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 58, title: "Король земли", genres: ["Романтика", "Комедия"], banner: "pictures/banner/58.jpg", images: ["pictures/screenshot/(58)/58 (1).jpg", "pictures/screenshot/(58)/58 (2).jpg", "pictures/screenshot/(58)/58 (3).jpg", "pictures/screenshot/(58)/58 (4).jpg", "pictures/screenshot/(58)/58 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 59, title: "Параллельные миры W", genres: ["Фэнтези", "Триллер", "Романтика"], banner: "pictures/banner/59.jpg", images: ["pictures/screenshot/(59)/59 (1).jpg", "pictures/screenshot/(59)/59 (2).jpg", "pictures/screenshot/(59)/59 (3).jpg", "pictures/screenshot/(59)/59 (4).jpg", "pictures/screenshot/(59)/59 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""}, 
  { id: 60, title: "Шеф Ким", genres: ["Комедия", "Бизнес"], banner: "pictures/banner/60.jpg", images: ["pictures/screenshot/(60)/60 (1).jpg", "pictures/screenshot/(60)/60 (2).jpg", "pictures/screenshot/(60)/60 (3).jpg", "pictures/screenshot/(60)/60 (4).jpg", "pictures/screenshot/(60)/60 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""}, 
  { id: 61, title: "Тридцать девять", genres: ["Драма", "Повседневность"], banner: "pictures/banner/61.jpg", images: ["pictures/screenshot/(61)/61 (1).jpg", "pictures/screenshot/(61)/61 (2).jpg", "pictures/screenshot/(61)/61 (3).jpg", "pictures/screenshot/(61)/61 (4).jpg", "pictures/screenshot/(61)/61 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 62, title: "Пиноккио", genres: ["Драма", "Романтика"], banner: "pictures/banner/62.jpg", images: ["pictures/screenshot/(62)/62 (1).jpg", "pictures/screenshot/(62)/62 (2).jpg", "pictures/screenshot/(62)/62 (3).jpg", "pictures/screenshot/(62)/62 (4).jpg", "pictures/screenshot/(62)/62 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""}, 
  { id: 63, title: "Листмейкер", genres: ["Музыка", "Драма"], banner: "pictures/banner/63.jpg", images: ["pictures/screenshot/(63)/63 (1).jpg", "pictures/screenshot/(63)/63 (2).jpg", "pictures/screenshot/(63)/63 (3).jpg", "pictures/screenshot/(63)/63 (4).jpg", "pictures/screenshot/(63)/63 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 64, title: "Путешествие Пак Ха-гён", genres: ["Повседневность"], banner: "pictures/banner/64.jpg", images: ["pictures/screenshot/(64)/64 (1).jpg", "pictures/screenshot/(64)/64 (2).jpg", "pictures/screenshot/(64)/64 (3).jpg", "pictures/screenshot/(64)/64 (4).jpg", "pictures/screenshot/(64)/64 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 65, title: "Минамдан: Заметки по делу", genres: ["Детектив", "Комедия"], banner: "pictures/banner/65.jpg", images: ["pictures/screenshot/(65)/65 (1).jpg", "pictures/screenshot/(65)/65 (2).jpg", "pictures/screenshot/(65)/65 (3).jpg", "pictures/screenshot/(65)/65 (4).jpg", "pictures/screenshot/(65)/65 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""}, 
  { id: 66, title: "Чудесный слух", genres: ["Экшен", "Фэнтези"], banner: "pictures/banner/66.jpg", images: ["pictures/screenshot/(66)/66 (1).jpg", "pictures/screenshot/(66)/66 (2).jpg", "pictures/screenshot/(66)/66 (3).jpg", "pictures/screenshot/(66)/66 (4).jpg", "pictures/screenshot/(66)/66 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 67, title: "Мой сосед — кумихо", genres: ["Фэнтези", "Романтика"], banner: "pictures/banner/67.jpg", images: ["pictures/screenshot/(67)/67 (1).jpg", "pictures/screenshot/(67)/67 (2).jpg", "pictures/screenshot/(67)/67 (3).jpg", "pictures/screenshot/(67)/67 (4).jpg", "pictures/screenshot/(67)/67 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 68, title: "Прорвемся", genres: ["Комедия", "Романтика", "Повседневность"], banner: "pictures/banner/68.jpg", images: ["pictures/screenshot/(68)/68 (1).jpg", "pictures/screenshot/(68)/68 (2).jpg", "pictures/screenshot/(68)/68 (3).jpg", "pictures/screenshot/(68)/68 (4).jpg", "pictures/screenshot/(68)/68 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79" }, 
  { id: 69, title: "Клетки Юми", genres: ["Романтика", "Комедия"], banner: "pictures/banner/69.jpg", images: ["pictures/screenshot/(69)/69 (1).jpg", "pictures/screenshot/(69)/69 (2).jpg", "pictures/screenshot/(69)/69 (3).jpg", "pictures/screenshot/(69)/69 (4).jpg", "pictures/screenshot/(69)/69 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 70, title: "Охотничьи псы", genres: ["Экшен", "Криминал"], banner: "pictures/banner/70.jpg", images: ["pictures/screenshot/(70)/70 (1).jpg", "pictures/screenshot/(70)/70 (2).jpg", "pictures/screenshot/(70)/70 (3).jpg", "pictures/screenshot/(70)/70 (4).jpg", "pictures/screenshot/(70)/70 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""}, 
  { id: 71, title: "Пентхаус", genres: ["Триллер", "Драма"], banner: "pictures/banner/71.jpg", images: ["pictures/screenshot/(71)/71 (1).jpg", "pictures/screenshot/(71)/71 (2).jpg", "pictures/screenshot/(71)/71 (3).jpg", "pictures/screenshot/(71)/71 (4).jpg", "pictures/screenshot/(71)/71 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 72, title: "Таксист", genres: ["Экшен", "Криминал"], banner: "pictures/banner/72.jpg", images: ["pictures/screenshot/(72)/72 (1).jpg", "pictures/screenshot/(72)/72 (2).jpg", "pictures/screenshot/(72)/72 (3).jpg", "pictures/screenshot/(72)/72 (4).jpg", "pictures/screenshot/(72)/72 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 73, title: "Привет, монстр", genres: ["Триллер", "Детектив"], banner: "pictures/banner/73.jpg", images: ["pictures/screenshot/(73)/73 (1).jpg", "pictures/screenshot/(73)/73 (2).jpg", "pictures/screenshot/(73)/73 (3).jpg", "pictures/screenshot/(73)/73 (4).jpg", "pictures/screenshot/(73)/73 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 74, title: "Алиса в Пограничье", genres: ["Фантастика", "Триллер"], banner: "pictures/banner/74.jpg", images: ["pictures/screenshot/(74)/74 (1).jpg", "pictures/screenshot/(74)/74 (2).jpg", "pictures/screenshot/(74)/74 (3).jpg", "pictures/screenshot/(74)/74 (4).jpg", "pictures/screenshot/(74)/74 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 75, title: "Полицейская академия", genres: ["Комедия", "Детектив"], banner: "pictures/banner/75.jpg", images: ["pictures/screenshot/(75)/75 (1).jpg", "pictures/screenshot/(75)/75 (2).jpg", "pictures/screenshot/(75)/75 (3).jpg", "pictures/screenshot/(75)/75 (4).jpg", "pictures/screenshot/(75)/75 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 76, title: "С богами: Два мира", genres: ["Фэнтези", "Драма"], banner: "pictures/banner/76.jpg", images: ["pictures/screenshot/(76)/76 (1).jpg", "pictures/screenshot/(76)/76 (2).jpg", "pictures/screenshot/(76)/76 (3).jpg", "pictures/screenshot/(76)/76 (4).jpg", "pictures/screenshot/(76)/76 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 77, title: "Моя жизнь снова", genres: ["Фэнтези", "Закон"], banner: "pictures/banner/77.jpg", images: ["pictures/screenshot/(77)/77 (1).jpg", "pictures/screenshot/(77)/77 (2).jpg", "pictures/screenshot/(77)/77 (3).jpg", "pictures/screenshot/(77)/77 (4).jpg", "pictures/screenshot/(77)/77 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 78, title: "Не слышу зла", type: "movie", duration: "103 мин", genres: ["Триллер"], banner: "pictures/banner/78.jpg", images: ["pictures/screenshot/(78)/78 (1).jpg", "pictures/screenshot/(78)/78 (2).jpg", "pictures/screenshot/(78)/78 (3).jpg", "pictures/screenshot/(78)/78 (4).jpg", "pictures/screenshot/(78)/78 (5).jpg"], status: "посмотрено", ratings: { kolya: 8, nika: 8 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 79, title: "Мы все мертвы", genres: ["Ужасы", "Зомби"], banner: "pictures/banner/79.jpg", images: ["pictures/screenshot/(79)/79 (1).jpg", "pictures/screenshot/(79)/79 (2).jpg", "pictures/screenshot/(79)/79 (3).jpg", "pictures/screenshot/(79)/79 (4).jpg", "pictures/screenshot/(79)/79 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 80, title: "Гость", genres: ["Ужасы", "Мистика"], banner: "pictures/banner/80.jpg", images: ["pictures/screenshot/(80)/80 (1).jpg", "pictures/screenshot/(80)/80 (2).jpg", "pictures/screenshot/(80)/80 (3).jpg", "pictures/screenshot/(80)/80 (4).jpg", "pictures/screenshot/(80)/80 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 81, title: "Городские легенды", genres: ["Драма"], banner: "pictures/banner/81.jpg", images: ["pictures/screenshot/(81)/81 (1).jpg", "pictures/screenshot/(81)/81 (2).jpg", "pictures/screenshot/(81)/81 (3).jpg", "pictures/screenshot/(81)/81 (4).jpg", "pictures/screenshot/(81)/81 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""}, 
  { id: 82, title: "Зов Ада", genres: ["Ужасы", "Триллер", "Фэнтези"], banner: "pictures/banner/82.jpg", images: ["pictures/screenshot/(82)/82 (1).jpg", "pictures/screenshot/(82)/82 (2).jpg", "pictures/screenshot/(82)/82 (3).jpg", "pictures/screenshot/(82)/82 (4).jpg", "pictures/screenshot/(82)/82 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 83, title: "Незнакомцы из Ада", genres: ["Ужасы", "Триллер", "Психология"], banner: "pictures/banner83.jpg", images: ["pictures/screenshot/(83)/83 (1).jpg", "pictures/screenshot/(83)/83 (2).jpg", "pictures/screenshot/(83)/83 (3).jpg", "pictures/screenshot/(83)/83 (4).jpg", "pictures/screenshot/(83)/83 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""}, 
  { id: 84, title: "Темная дыра", genres: ["Ужасы", "Фантастика"], banner: "pictures/banner/84.jpg", images: ["pictures/screenshot/(84)/84 (1).jpg", "pictures/screenshot/(84)/84 (2).jpg", "pictures/screenshot/(84)/84 (3).jpg", "pictures/screenshot/(84)/84 (4).jpg", "pictures/screenshot/(84)/84 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 85, title: "Во имя мести", type: "tv", seasons:[8], genres: ["Экшен", "Криминал"], banner: "pictures/banner/85.jpg", images: ["pictures/screenshot/(85)/85 (1).jpg", "pictures/screenshot/(85)/85 (2).jpg", "pictures/screenshot/(85)/85 (3).jpg", "pictures/screenshot/(85)/85 (4).jpg", "pictures/screenshot/(85)/85 (5).jpg"], status: "посмотрено", ratings: { kolya: 9, nika: 9.5 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 86, title: "Триумф", genres: ["Драма", "Триллер"], banner: "pictures/banner/86.jpg", images: ["pictures/screenshot/(86)/86 (1).jpg", "pictures/screenshot/(86)/86 (2).jpg", "pictures/screenshot/(86)/86 (3).jpg", "pictures/screenshot/(86)/86 (4).jpg", "pictures/screenshot/(86)/86 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 87, title: "Кто-то", genres: ["Триллер", "Криминал"], banner: "pictures/banner/87.jpg", images: ["pictures/screenshot/(87)/87 (1).jpg", "pictures/screenshot/(87)/87 (2).jpg", "pictures/screenshot/(87)/87 (3).jpg", "pictures/screenshot/(87)/87 (4).jpg", "pictures/screenshot/(87)/87 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 88, title: "На пути к небесам", genres: ["Драма", "Повседневность"], banner: "pictures/banner/88.jpg", images: ["pictures/screenshot/(88)/88 (1).jpg", "pictures/screenshot/(88)/88 (2).jpg", "pictures/screenshot/(88)/88 (3).jpg", "pictures/screenshot/(88)/88 (4).jpg", "pictures/screenshot/(88)/88 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 89, title: "Дневник психопата", genres: ["Комедия", "Триллер"], banner: "pictures/banner/89.jpg", images: ["pictures/screenshot/(89)/89 (1).jpg", "pictures/screenshot/(89)/89 (2).jpg", "pictures/screenshot/(89)/89 (3).jpg", "pictures/screenshot/(89)/89 (4).jpg", "pictures/screenshot/(89)/89 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 90, title: "Меморист", genres: ["Детектив", "Фэнтези"], banner: "pictures/banner/90.jpg", images: ["pictures/screenshot/(90)/90 (1).jpg", "pictures/screenshot/(90)/90 (2).jpg", "pictures/screenshot/(90)/90 (3).jpg", "pictures/screenshot/(90)/90 (4).jpg", "pictures/screenshot/(90)/90 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 91, title: "Монстр", genres: ["Триллер", "Детектив"], banner: "pictures/banner/91.jpg", images: ["pictures/screenshot/(91)/91 (1).jpg", "pictures/screenshot/(91)/91 (2).jpg", "pictures/screenshot/(91)/91 (3).jpg", "pictures/screenshot/(91)/91 (4).jpg", "pictures/screenshot/(91)/91 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 92, title: "Слепцы", genres: ["Триллер", "Детектив"], banner: "pictures/banner/92.jpg", images: ["pictures/screenshot/(92)/92 (1).jpg", "pictures/screenshot/(92)/92 (2).jpg", "pictures/screenshot/(92)/92 (3).jpg", "pictures/screenshot/(92)/92 (4).jpg", "pictures/screenshot/(92)/92 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 93, title: "Незнакомец", genres: ["Детектив", "Закон"], banner: "pictures/banner/93.jpg", images: ["pictures/screenshot/(93)/93 (1).jpg", "pictures/screenshot/(93)/93 (2).jpg", "pictures/screenshot/(93)/93 (3).jpg", "pictures/screenshot/(93)/93 (4).jpg", "pictures/screenshot/(93)/93 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 94, title: "К2", genres: ["Экшен", "Романтика"], banner: "pictures/banner/94.jpg", images: ["pictures/screenshot/(94)/94 (1).jpg", "pictures/screenshot/(94)/94 (2).jpg", "pictures/screenshot/(94)/94 (3).jpg", "pictures/screenshot/(94)/94 (4).jpg", "pictures/screenshot/(94)/94 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9" , description: ""},
  { id: 95, title: "Молодые копы", genres: ["Комедия", "Экшен"], banner: "pictures/banner/95.jpg", images: ["pictures/screenshot/(95)/95 (1).jpg", "pictures/screenshot/(95)/95 (2).jpg", "pictures/screenshot/(95)/95 (3).jpg", "pictures/screenshot/(95)/95 (4).jpg", "pictures/screenshot/(95)/95 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 96, title: "Игра в кальмара", genres: ["Триллер", "Драма"], banner: "pictures/banner/96.jpg", images: ["pictures/screenshot/(96)/96 (1).jpg", "pictures/screenshot/(96)/96 (2).jpg", "pictures/screenshot/(96)/96 (3).jpg", "pictures/screenshot/(96)/96 (4).jpg", "pictures/screenshot/(96)/96 (5).jpg"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5" , description: ""},
  { id: 97, title: "Влюбиться в Сун Джон", genres: ["Романтика", "Комедия", "Драма"], banner: "pictures/banner/97.jpg", images: ["pictures/screenshot/(97)/97 (1).jpg", "pictures/screenshot/(97)/97 (2).jpg", "pictures/screenshot/(97)/97 (3).jpg", "pictures/screenshot/(97)/97 (4).jpg", "pictures/screenshot/(97)/97 (5).jpg"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""}, 
  { id: 98, title: "Пока ты спишь", genres: ["Романтика", "Фэнтези", "Детектив"], banner: "pictures/banner/98.jpg", images: ["pictures/screenshot/(98)/98 (1).jpg", "pictures/screenshot/(98)/98 (2).jpg", "pictures/screenshot/(98)/98 (3).jpg", "pictures/screenshot/(98)/98 (4).jpg", "pictures/screenshot/(98)/98 (5).jpg"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""}, 
  { id: 100, title: "Рождественская песня", genres: ["Триллер", "Драма"], banner: "pictures/banner/100.jpg", images: ["pictures/screenshot/(100)/100 (1).jpg", "pictures/screenshot/(100)/100 (2).jpg", "pictures/screenshot/(100)/100 (3).jpg", "pictures/screenshot/(100)/100 (4).jpg", "pictures/screenshot/(100)/100 (5).jpg"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: "" },
  { id: 99, title: "Подозрительный партнер", genres: ["Романтика", "Комедия"], banner: "pictures/banner/99.jpg", images: ["pictures/screenshot/(99)/99 (1).jpg", "pictures/screenshot/(99)/99 (2).jpg", "pictures/screenshot/(99)/99 (3).jpg", "pictures/screenshot/(99)/99 (4).jpg", "pictures/screenshot/(99)/99 (5).jpg"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 101, title: "И Джэ, скоро умрёт", genres: ["Фэнтези", "Триллер"], banner: "pictures/banner/101.jpg", images: ["pictures/screenshot/(101)/101 (1).jpg", "pictures/screenshot/(101)/101 (2).jpg", "pictures/screenshot/(101)/101 (3).jpg", "pictures/screenshot/(101)/101 (4).jpg", "pictures/screenshot/(101)/101 (5).jpg"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 102, title: "Суперчудаки", genres: ["Комедия"], banner: "pictures/banner/102.jpg", images: ["pictures/screenshot/(102)/102 (1).jpg", "pictures/screenshot/(102)/102 (2).jpg", "pictures/screenshot/(102)/102 (3).jpg", "pictures/screenshot/(102)/102 (4).jpg", "pictures/screenshot/(102)/102 (5).jpg"], status: "смотрим", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 103, title: "Проклятие «Зов могилы»", genres: ["Ужасы", "Триллер"], banner: "pictures/banner/103.jpg", images: ["pictures/screenshot/(103)/103 (1).jpg", "pictures/screenshot/(103)/103 (2).jpg", "pictures/screenshot/(103)/103 (3).jpg", "pictures/screenshot/(103)/103 (4).jpg", "pictures/screenshot/(103)/103 (5).jpg"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
];
const wheelItems = doramasData.filter(dorama => dorama.status === "запланировано");


function renderDoramaRatings(dorama) {
  const ratingsContainer = document.getElementById('dorama-ratings');
  if (!ratingsContainer) return;

  const kolyaRating = dorama.ratings ? dorama.ratings.kolya : 0;
  const nikaRating = dorama.ratings ? dorama.ratings.nika : 0;

  const kolyaPercent = kolyaRating * 10;
  const nikaPercent = nikaRating * 10;

  ratingsContainer.innerHTML = `
    <div class="ratings-block">
      <div class="rating-row">
        <span class="rating-author">Оценка Коли:</span>
        <div class="stars-outer">
          <div class="stars-inner kolya-fill" style="width: ${kolyaPercent}%"></div>
        </div>
        <span class="rating-val">(${kolyaRating})</span>
      </div>
      <div class="rating-row">
        <span class="rating-author">Оценка Ники:</span>
        <div class="stars-outer">
          <div class="stars-inner nika-fill" style="width: ${nikaPercent}%"></div>
        </div>
        <span class="rating-val">(${nikaRating})</span>
      </div>
    </div>
  `;
}