const doramasData = [
  { id: 1, title: "Силачка До Бон-сун", genres: ["Комедия", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 2, title: "Что случилось с секретарем Ким?", genres: ["Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 3, title: "Продавец на полставки", genres: ["Комедия"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 4, title: "Демон", genres: ["Фэнтези"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 5, title: "Наследники", genres: ["Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 6, title: "Фея тяжелой атлетики Ким Бок-чжу", genres: ["Спорт", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 7, title: "Уведомление о любви", genres: ["Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 8, title: "Каннамская красотка", genres: ["Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 9, title: "Королева слез", genres: ["Драма", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 10, title: "Вернуться в 1988", genres: ["Комедия", "Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 11, title: "Алхимия душ", genres: ["Фэнтези", "Экшен"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 12, title: "Плохая мать", genres: ["Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 13, title: "Призрачный доктор", genres: ["Фэнтези", "Медицина"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 14, title: "Врачебная мудрость", genres: ["Медицина", "Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 15, title: "Завтра", genres: ["Фэнтези"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 16, title: "Хилер", genres: ["Экшен", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 17, title: "Потомки солнца", genres: ["Романтика", "Военный"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 18, title: "Мама", genres: ["Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 19, title: "Учитель Ким, доктор романтик", genres: ["Медицина"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 20, title: "Хватай Сон Джэ и беги", genres: ["Романтика", "Фэнтези"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 21, title: "Я псих, но это нормально", genres: ["Психология", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 22, title: "Время взывает к тебе", genres: ["Фэнтези", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 23, title: "Итэвон Класс", genres: ["Бизнес", "Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 24, title: "И солнце снова взойдет", genres: ["Драма", "Медицина"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 25, title: "Любовное приземление", genres: ["Романтика", "Комедия"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 26, title: "Мышь", genres: ["Триллер", "Детектив"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 27, title: "Дьявольский судья", genres: ["Детектив", "Закон"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""}, 
  { id: 28, title: "Легенда синего моря", genres: ["Фэнтези", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 29, title: "Любовное сражение", genres: ["Комедия", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 30, title: "Болтун", genres: ["Триллер", "Закон"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 31, title: "Добро пожаловать в Самдали", genres: ["Романтика", "Повседневность"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 32, title: "Военный прокурор Доберман", genres: ["Экшен", "Закон"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 33, title: "Разрушение к вашим услугам", genres: ["Фэнтези", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 34, title: "Счастье", genres: ["Триллер", "Зомби"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 35, title: "Я не робот", genres: ["Романтика", "Комедия"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 36, title: "Необычный адвокат У Ён У", genres: ["Закон", "Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 37, title: "Работай позже, пей сейчас", genres: ["Комедия", "Повседневность"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "брошено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 38, title: "Большое зло", genres: ["Триллер"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 39, title: "Винченцо", genres: ["Криминал", "Комедия"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 40, title: "Мальчики краше цветов", genres: ["Романтика", "Школа"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 41, title: "Цветок зла", genres: ["Триллер", "Детектив"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 42, title: "Убей меня, исцели меня", genres: ["Психология", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 43, title: "Плохой и сумасшедший", genres: ["Экшен", "Комедия"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 44, title: "Сказание о кумихо (История девятихвостого лиса)", genres: ["Фэнтези"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "брошено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 45, title: "Я тебя слышу", genres: ["Романтика", "Закон"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 46, title: "Деловое предложение", genres: ["Романтика", "Комедия"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 47, title: "Магазин для киллеров", genres: ["Экшен", "Триллер"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 48, title: "Мой демон", genres: ["Фэнтези", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 49, title: "Суждено быть с тобой", genres: ["Романтика", "Фэнтези"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 50, title: "Хваюги", genres: ["Фэнтези", "Романтика", "Комедия"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 51, title: "Отель Дель Луна", genres: ["Фэнтези"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 52, title: "Ночная фотостудия", genres: ["Фэнтези", "Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 53, title: "Врачи", genres: ["Медицина", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 54, title: "Истинная красота", genres: ["Романтика", "Школа"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 55, title: "Жизнь на Марсе", genres: ["Детектив", "Фантастика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 56, title: "Наше любимое лето", genres: ["Романтика", "Повседневность"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 57, title: "Кто ты: Школа 2015", genres: ["Школа", "Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 58, title: "Король земли", genres: ["Романтика", "Комедия"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 59, title: "Параллельные миры W", genres: ["Фэнтези", "Триллер", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""}, 
  { id: 60, title: "Шеф Ким", genres: ["Комедия", "Бизнес"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""}, 
  { id: 61, title: "Тридцать девять", genres: ["Драма", "Повседневность"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 62, title: "Пиноккио", genres: ["Драма", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""}, 
  { id: 63, title: "Листмейкер", genres: ["Музыка", "Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 64, title: "Путешествие Пак Ха-гён", genres: ["Повседневность"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 65, title: "Минамдан: Заметки по делу", genres: ["Детектив", "Комедия"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""}, 
  { id: 66, title: "Чудесный слух", genres: ["Экшен", "Фэнтези"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 67, title: "Мой сосед — кумихо", genres: ["Фэнтези", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 68, title: "Прорвемся", genres: ["Комедия", "Романтика", "Повседневность"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79" }, 
  { id: 69, title: "Клетки Юми", genres: ["Романтика", "Комедия"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 70, title: "Охотничьи псы", genres: ["Экшен", "Криминал"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""}, 
  { id: 71, title: "Пентхаус", genres: ["Триллер", "Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 72, title: "Таксист", genres: ["Экшен", "Криминал"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 73, title: "Привет, монстр", genres: ["Триллер", "Детектив"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 74, title: "Алиса в Пограничье", genres: ["Фантастика", "Триллер"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 75, title: "Полицейская академия", genres: ["Комедия", "Детектив"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 76, title: "С богами: Два мира", genres: ["Фэнтези", "Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 77, title: "Моя жизнь снова", genres: ["Фэнтези", "Закон"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 78, title: "Не слышу зла", genres: ["Триллер"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 79, title: "Мы все мертвы", genres: ["Ужасы", "Зомби"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 80, title: "Гость", genres: ["Ужасы", "Мистика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 81, title: "Городские легенды", genres: ["Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""}, 
  { id: 82, title: "Зов Ада", genres: ["Ужасы", "Триллер", "Фэнтези"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 83, title: "Незнакомцы из Ада", genres: ["Ужасы", "Триллер", "Психология"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""}, 
  { id: 84, title: "Темная дыра", genres: ["Ужасы", "Фантастика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 85, title: "Во имя мести", genres: ["Экшен", "Криминал"], banner: "pictures/banner/85.jpg", images: ["pictures/screenshot/id(85)/1.jpg", "pictures/screenshot/id(85)/2.jpg", "pictures/screenshot/id(85)/3.jpg", "pictures/screenshot/id(85)/4.jpg", "pictures/screenshot/id(85)/5.jpg"], status: "посмотрено", ratings: { kolya: 9, nika: 9.5 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 86, title: "Триумф", genres: ["Драма", "Триллер"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 87, title: "Кто-то", genres: ["Триллер", "Криминал"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 88, title: "На пути к небесам", genres: ["Драма", "Повседневность"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 89, title: "Дневник психопата", genres: ["Комедия", "Триллер"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 90, title: "Меморист", genres: ["Детектив", "Фэнтези"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 91, title: "Монстр", genres: ["Триллер", "Детектив"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 92, title: "Слепцы", genres: ["Триллер", "Детектив"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 93, title: "Незнакомец", genres: ["Детектив", "Закон"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 94, title: "К2", genres: ["Экшен", "Романтика"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9" , description: ""},
  { id: 95, title: "Молодые копы", genres: ["Комедия", "Экшен"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""},
  { id: 96, title: "Игра в кальмара", genres: ["Триллер", "Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5" , description: ""},
  { id: 97, title: "Влюбиться в Сун Джон", genres: ["Романтика", "Комедия", "Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""}, 
  { id: 98, title: "Пока ты спишь", genres: ["Романтика", "Фэнтези", "Детектив"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: ""}, 
  { id: 99, title: "Подозрительный партнер", genres: ["Романтика", "Комедия"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 100, title: "Рождественская песня", genres: ["Триллер", "Драма"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "запланировано", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#ff4d79", description: "" },
  { id: 101, title: "И Джэ, скоро умрёт", genres: ["Фэнтези", "Триллер"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#9b5de5", description: ""},
  { id: 102, title: "Суперчудаки", genres: ["Комедия"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "смотрим", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
  { id: 103, title: "Проклятие «Зов могилы»", genres: ["Ужасы", "Триллер"], banner: "МЕСТО_ДЛЯ_БАННЕРА", images: ["КАДР_1", "КАДР_2", "КАДР_3", "КАДР_4", "КАДР_5"], status: "посмотрено", ratings: { kolya: 0, nika: 0 }, ourReviews: { kolya: "", nika: "" }, color: "#00bbf9", description: ""},
];
const wheelItems = doramasData.filter(dorama => dorama.status === "запланировано");


function renderDoramaRatings(dorama) {
  const ratingsContainer = document.getElementById('dorama-ratings');
  if (!ratingsContainer) return;

  const kolyaRating = dorama.ratings ? dorama.ratings.kolya : 0;
  const nikaRating = dorama.ratings ? dorama.ratings.nika : 0;

  // 10 баллов = 100% ширины, 7.5 баллов = 75% ширины и т.д.
  const kolyaPercent = kolyaRating * 10;
  const nikaPercent = nikaRating * 10;

  ratingsContainer.innerHTML = `
    <div class="ratings-block">
      <div class="rating-row">
        <span class="rating-author">Оценка Коли:</span>
        <div class="stars-outer">
          <div class="stars-inner kolya-fill" style="width: ${kolyaPercent}%"></div>
        </div>
        <span class="rating-val">(${kolyaRating})</span>
      </div>
      <div class="rating-row">
        <span class="rating-author">Оценка Ники:</span>
        <div class="stars-outer">
          <div class="stars-inner nika-fill" style="width: ${nikaPercent}%"></div>
        </div>
        <span class="rating-val">(${nikaRating})</span>
      </div>
    </div>
  `;
}